#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

BIN_NAME_PREFIX="terraform-provider-harvester"
BUILD_DIR="./build"
BUILD_BIN_DIR="${BUILD_DIR}/bin"
if [ -z "$(ls -A ${BUILD_BIN_DIR})" ]; then
  exit 0
fi

VERSION_NO_V=$(echo $VERSION | sed "s/^[v|V]//")
echo "==> Packaging binaries version ${VERSION_NO_V} ..."

DIST=$(pwd)/dist/artifacts

mkdir -p $DIST/${VERSION}

for i in ${BUILD_DIR}/bin/*; do
    if [ ! -e $i ]; then
        continue
    fi

    BASE=${BUILD_DIR}/archive
    DIR=${BASE}/${VERSION}

    rm -rf $BASE
    mkdir -p $BASE $DIR

    EXT=
    if [[ $i =~ .*windows.* ]]; then
        EXT=.exe
    fi

    cp $i ${DIR}/${BIN_NAME_PREFIX}_${VERSION}${EXT}

    (
        cd $DIR
        NAME=$(basename $i | cut -f1 -d_)
        ARCH=$(basename $i | cut -f2,3 -d_ | cut -f1 -d.)
        ARCHIVE=${NAME}_${VERSION_NO_V}_${ARCH}.zip
        echo "Packaging $DIST/${VERSION}/${ARCHIVE} ..."
        zip -q $DIST/${VERSION}/${ARCHIVE} *
    )
done

(
    cd $DIST/${VERSION}/
    shasum -a 256 * > ${BIN_NAME_PREFIX}_${VERSION_NO_V}_SHA256SUMS
)